# *Manejo de Excepciones con Python*

üö® Este material fue creado por Ana Julia Velez Rueda y como todo el repositorio se encuentra bajo licencia 
[Creative Commons Attribution-ShareAlike 4.0 International License][cc-by-sa].

[![CC BY-SA 4.0][cc-by-sa-image]][cc-by-sa]

[cc-by-sa]: http://creativecommons.org/licenses/by-sa/4.0/
[cc-by-sa-image]: https://licensebuttons.net/l/by-sa/4.0/88x31.png
[cc-by-sa-shield]: https://img.shields.io/badge/License-CC%20BY--SA%204.0-lightgrey.svg


# Guias de Trabajo
* [1. La excepci√≥n hace a la regla](#1-intro)
* [2. Errores de Sintaxis](#2-sintax_error)
* [3. Excepciones](#3-exceptions)
* [4. Con intentar no se pierde nada](#4-try)
* [5. Excepciones personalizadas](#5-raise)


[1. La excepci√≥n hace a la regla](#1-intro)
Si estuviste haciendo bien las cosas hasta aqu√≠, te habr√°s equivocado ¬°y mucho! En todo proceso de aprendizaje los ‚Äòerrores‚Äô tienen un rol muy importante: nos plantean nuevos interrogantes, nos acercan a nuevas hip√≥tesis y sobre todo nos dan oportunidades para seguir aprendiendo. 
En la programaci√≥n los ‚Äòerrores‚Äô tambi√©n importan, ¬°y mucho! Son una suerte de comunicaci√≥n con la m√°quina, que nos advierte cuando no funciona algo de lo que intentamos hacer.
Existen (al menos) dos tipos diferentes de errores en Python: errores de sintaxis y excepciones. Con cada tipo de error la m√°quina nos indica qu√© es lo que puede estar fallando de nuestro c√≥digo. 
No tengas miedo de equivocarte, ¬°no se rompe nada! Y como dir√≠a la se√±orita Ricitos del Autob√∫s M√°gico: _a cometer errores, tomar oportunidades y rockear con Python, que donde termina la carretera comienza la aventura!_

[2. Errores de Sintaxis](#2-sintax_error)
Cuando existen errores en el c√≥digo se detiene la ejecuci√≥n del programa que hemos creado. Uno de los tipos de errores mas frecuente al iniciarnos en la programaci√≥n con Python son los errores de sintaxis, o tambi√©n conocidos como errores de interpretaci√≥n. ¬øA ver si te suena?

```Python
>>> print(Hola mundo')
  File "<stdin>", line 1
    print(Hola mundo')
               ^
SyntaxError: invalid syntax
```

Si observamos el error este tiene en su mensaje informaci√≥n que nos permitir√° encontar el origen del problema.

>
> üßó‚Äç‚ôÄÔ∏èDesafio I: Descarg√° y ejecut√° el [`script1_manejo_errores.py`](https://github.com/AJVelezRueda/Fundamentos_de_informatica/blob/master/Python_intro/Recursos_anexos/script1_manejo_errores.py)
>
> Para pensar ü§î: ¬øQu√© tipo de error se obtiene al ejecutar el programa? ¬øEn d√≥nde se encuentra el error? ¬øC√≥mo te das cuenta? 
>

Como has visto el int√©rprete de Python imprime la l√≠nea responsable del error y muestra una flecha el lugar donde se detect√≥ el error. El error ha sido detectado en el elemento que precede a la flecha. En nuestro ejemplo, el error fu√© detectado al ejecutar la funci√≥n print(), ya que faltan las comillas que abre el string.


[3. Excepciones](#3-exceptions)

Sin embargo, a√∫n cuando nuestro c√≥digo sea sint√°cticamente correcto, puede generar errores de ejecuciones. Los errores detectados durante la ejecuci√≥n se llaman excepciones. Existen distintos tipos de excepciones y generalmente el tipo de excepci√≥n se imprime como parte del mensaje, al surgir la excepci√≥n:

```Python
>>> 3 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero

```

```Python
>>> print(divisor)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'divisor' is not defined
```
>
> Para pensar ü§î: ¬øQu√© nos dice el mensaje de excepci√≥n? ¬øQu√© es la excepci√≥n de nombre? 
>

```Python
>>> 0 + "2"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

>
> Para pensar ü§î: ¬øQu√© nos dice el √∫ltimo mensaje de excepci√≥n? ¬øQu√© es la excepci√≥n de tipo? 
>


[4. Con intentar no se pierde nada](#4-try)

La pregunta que se estar√°n haciendo es ¬øComo podemos preveer estas excepciones para que no se interrumpa la ejecuci√≥n de nuestro programa? Bueno, para el manejo de excepciones Python nos provee palabras reservadas, que nos permiten manejar las excepciones que puedan surgir y tomar acciones que evitan la interrupci√≥n del programa o permitan especificar informaci√≥n adicional antes de interrumpir el programa.
Una de las palabras reservadas es try, esta nos permite "encapsular" un bloque de c√≥digo para interceptar e identificar excepciones. Si se produce un error dentro de la declaraci√≥n try-except, se omite una excepci√≥n y se ejecuta el bloque de c√≥digo que maneja la excepci√≥n. 

```Python
try:
    # aqu√≠ ponemos el c√≥digo que puede lanzar excepciones
except:
    # entrar√° aqu√≠ en caso que se haya producido una excepci√≥n
```

>
>Para pensar ü§î: ¬øQu√© tipo de excepci√≥n se maneja en el c√≥digo anterior?
>

Vamos a trabajar con un ejemplo:

>
> üßó‚Äç‚ôÄÔ∏èDesafio II: Cre√° una funci√≥n denominada _mitades_ que tenga como argumento un n√∫mero e imprima el resultado de la divisi√≥n de ese n√∫mero por 2
>
>Para pensar ü§î: ¬øQu√© crees que ocurrir√° cuando ingresas un 9 como par√°metro? ¬øY con un 0?
>
> üßó‚Äç‚ôÄÔ∏èDesafio III: ¬øC√≥mo mejorar√≠as tu funci√≥n para que sea capaz de manejar el error de la divisi√≥n por cero? Reescrib√≠ la funci√≥n incorporando una declaraci√≥n try-except
>


[5. Excepciones personalizadas](#5-raise)

En algunos casos, puede ser necesario crear excepciones personalizadas o forzar que ocurra una excepci√≥n espec√≠fica dado un contexto.  La sentencia _raise_, se puede indicar el tipo de excepci√≥n que deseamos lanzar y el mensaje de que queremos brindarle al usuario:


```Python
def check_int_type():
  if type(x)  != int:
    raise TypeError("Only integers are allowed") 
```
